# -*- coding: utf-8 -*-
"""NeoBank Security Middleware.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfN-OpwzV_Ra_4Wm2Y1SSxQVpwT59BDz
"""

import time
import sqlite3

class NeoBankSecurityMiddleware:
    def __init__(self, request_limit=3, time_window=5):
        # DDoS and SYN Flood Mitigation State
        self.ip_records = {}
        self.request_limit = request_limit
        self.time_window = time_window
        self.blacklist = set()

    def check_rate_limit(self, ip_address):
        """Mitigates SYN Flood by enforcing strict rate limits on each IP address"""
        if ip_address in self.blacklist:
            return False, "[BLOCKED] IP has been widely blacklisted."

        current_time = time.time()
        if ip_address not in self.ip_records:
            self.ip_records[ip_address] = []

        # Sliding window: remove requests older than the time_window
        self.ip_records[ip_address] = [
            t for t in self.ip_records[ip_address]
            if current_time - t < self.time_window
        ]
        self.ip_records[ip_address].append(current_time)

        if len(self.ip_records[ip_address]) > self.request_limit:
            self.blacklist.add(ip_address)
            return False, "[ALERT] Rate limit exceeded! IP added to Blacklist."

        return True, "[ALLOWED] Traffic normal."

# Simulation Execution
middleware = NeoBankSecurityMiddleware(request_limit=3, time_window=5)